apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-service-helloworld-deploy
  labels:
    app: aks-service-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-service-helloworld-pod
  template:
    metadata:
      labels:
        app: aks-service-helloworld-pod
    spec:
      containers:
        - name: fastapi
          image: ewpacrregistry.azurecr.io/aks-service-helloworld:6b2b83d78c064a413a22b733e2120d920fb3d79a
          ports:
            - containerPort: 80
