apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-service-helloworld-deploy
  labels:
    app: aks-service-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-service-helloworld-pod
  template:
    metadata:
      labels:
        app: aks-service-helloworld-pod
    spec:
      containers:
        - name: fastapi
          image: ewpacrregistry.azurecr.io/aks-service-helloworld:a403c6ff2d6fe0eac8ba8a56507ff8f91333fb65
          ports:
            - containerPort: 80
