apiVersion: v1
kind: Service
metadata:
  name: faks-service-helloworld-svc
spec:
  selector:
    app: aks-service-helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
