apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks-service-helloworld
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/vilgen/aks-gitops.git
    targetRevision: main
    path: base

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
